CONFIG_USE_DT_CODE_PARTITION=y

CONFIG_ADC=y
CONFIG_GPIO=y

CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_LOG=n

CONFIG_BT=n
CONFIG_BT_PERIPHERAL=n
CONFIG_BT_NUS=n
CONFIG_BT_NUS_SECURITY_ENABLED=n

CONFIG_HEAP_MEM_POOL_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_ASSERT=y

CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_LSM6DSL=y
